//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlLinkChecker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RscLiterals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RscLiterals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrlLinkChecker.RscLiterals", typeof(RscLiterals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string CounterLabel_Default {
            get {
                return ResourceManager.GetString("CounterLabel_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string CounterLabel_RunningFormat {
            get {
                return ResourceManager.GetString("CounterLabel_RunningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Html.
        /// </summary>
        internal static string Error_BadHtml {
            get {
                return ResourceManager.GetString("Error_BadHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open in Excel. Data has been copied to the clipboard. \n Try pasting into Excel manually.
        /// </summary>
        internal static string Error_ExcelClipboad {
            get {
                return ResourceManager.GetString("Error_ExcelClipboad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http.
        /// </summary>
        internal static string Link_ProtocolPrefix {
            get {
                return ResourceManager.GetString("Link_ProtocolPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string ListView_Column1Label {
            get {
                return ResourceManager.GetString("ListView_Column1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        internal static string ListView_Column1Width {
            get {
                return ResourceManager.GetString("ListView_Column1Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string ListView_Column2Label {
            get {
                return ResourceManager.GetString("ListView_Column2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string ListView_Column2Width {
            get {
                return ResourceManager.GetString("ListView_Column2Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ListView_Column3Label {
            get {
                return ResourceManager.GetString("ListView_Column3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 340.
        /// </summary>
        internal static string ListView_Column3Width {
            get {
                return ResourceManager.GetString("ListView_Column3Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badlinks.txt.
        /// </summary>
        internal static string Parse_BadLinksFileName {
            get {
                return ResourceManager.GetString("Parse_BadLinksFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Volume Warning.
        /// </summary>
        internal static string Parse_LinkVolumeLabel {
            get {
                return ResourceManager.GetString("Parse_LinkVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} links. It may take a while to check them all. \n\n Do you want to proceed?.
        /// </summary>
        internal static string Parse_LinkVolumeWarning {
            get {
                return ResourceManager.GetString("Parse_LinkVolumeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmptyResults.
        /// </summary>
        internal static string Parse_NoLinksLabel {
            get {
                return ResourceManager.GetString("Parse_NoLinksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No url links found. Please check your Link Format choice..
        /// </summary>
        internal static string Parse_NoLinksWarning {
            get {
                return ResourceManager.GetString("Parse_NoLinksWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t.
        /// </summary>
        internal static string Parse_SourceFileLineSplitter {
            get {
                return ResourceManager.GetString("Parse_SourceFileLineSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string Result_Fail {
            get {
                return ResourceManager.GetString("Result_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Result_Ok {
            get {
                return ResourceManager.GetString("Result_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string Result_Splitter {
            get {
                return ResourceManager.GetString("Result_Splitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET.
        /// </summary>
        internal static string WebRequest_HeaderComparedValue {
            get {
                return ResourceManager.GetString("WebRequest_HeaderComparedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        internal static string WebRequest_HeaderRedirectResponseCodeMax {
            get {
                return ResourceManager.GetString("WebRequest_HeaderRedirectResponseCodeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.
        /// </summary>
        internal static string WebRequest_HeaderRedirectResponseCodeMin {
            get {
                return ResourceManager.GetString("WebRequest_HeaderRedirectResponseCodeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAD.
        /// </summary>
        internal static string WebRequest_HeaderUpdatedValue {
            get {
                return ResourceManager.GetString("WebRequest_HeaderUpdatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string WebRequest_MaxRedirectCount {
            get {
                return ResourceManager.GetString("WebRequest_MaxRedirectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string WebRequest_TimeoutSecondsDefault {
            get {
                return ResourceManager.GetString("WebRequest_TimeoutSecondsDefault", resourceCulture);
            }
        }
    }
}
